<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>BAIOS.Reports</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\BAIOS.Core\BAIOS.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Assets\logo.png">
      <LogicalName>BAIOS.logo.png</LogicalName>
    </EmbeddedResource>
  </ItemGroup>
</Project>
