<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>BAIOS.Diagnostics</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\BAIOS.Core\BAIOS.Core.csproj" />
    <PackageReference Include="System.Management" Version="8.0.0" />
    <PackageReference Include="System.ServiceProcess.ServiceController" Version="8.0.1" />
  </ItemGroup>
</Project>
